import { NextRequest, NextResponse } from "next/server";
import { createServerSupabase } from "@/lib/supabase/server";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: NextRequest) {
  const supabase = await createServerSupabase();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const { company_id, name, email, role, pay_amount } = await request.json();

    // Verify company ownership
    const { data: company } = await supabase
      .from("companies")
      .select("name")
      .eq("id", company_id)
      .eq("owner_id", user.id)
      .single();

    if (!company) {
      return NextResponse.json({ error: "Company not found" }, { status: 404 });
    }

    // Create recipient record (invite_token auto-generated by trigger)
    const { data: recipient, error } = await supabase
      .from("recipients")
      .insert({
        company_id,
        name,
        email,
        role,
        pay_amount,
        status: "pending",
        invite_sent_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) throw error;

    // Send invite email via Resend
    const inviteUrl = `${process.env.NEXT_PUBLIC_APP_URL}/invite/${recipient.invite_token}`;

    await resend.emails.send({
      from: "StablePay <noreply@stablepay.me>",
      to: email,
      subject: `${company.name} invited you to get paid via StablePay`,
      html: `
        <div style="font-family: 'DM Sans', Arial, sans-serif; max-width: 480px; margin: 0 auto; background: #0B1120; color: #E8EDF5; padding: 32px; border-radius: 16px;">
          <div style="text-align: center; margin-bottom: 24px;">
            <div style="display: inline-block; width: 40px; height: 40px; border-radius: 10px; background: linear-gradient(135deg, #00D67E, #7C5CFC); color: white; font-weight: 800; font-size: 18px; line-height: 40px;">S</div>
          </div>
          <h1 style="text-align: center; font-size: 22px; margin-bottom: 8px;">You've been invited!</h1>
          <p style="text-align: center; color: #7A8BA8; font-size: 14px; margin-bottom: 24px;">
            <strong style="color: #E8EDF5;">${company.name}</strong> wants to pay you via StablePay — the simplest way to receive digital dollar payments.
          </p>
          <div style="background: #111B2E; border: 1px solid #1E2D44; border-radius: 12px; padding: 16px; margin-bottom: 24px;">
            <div style="color: #7A8BA8; font-size: 12px; margin-bottom: 4px;">YOUR ROLE</div>
            <div style="font-weight: 600;">${role}</div>
          </div>
          <a href="${inviteUrl}" style="display: block; text-align: center; padding: 14px; border-radius: 12px; background: linear-gradient(135deg, #00D67E, #00B368); color: white; font-weight: 700; text-decoration: none; font-size: 15px;">
            Accept Invite & Set Up
          </a>
          <p style="text-align: center; color: #4A5B73; font-size: 11px; margin-top: 16px;">
            Powered by 💧 Spraay Protocol
          </p>
        </div>
      `,
    });

    return NextResponse.json({ success: true, recipient_id: recipient.id });
  } catch (error: any) {
    console.error("[API] Invite error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to send invite" },
      { status: 500 }
    );
  }
}
